version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "728035916027"
    ECR_REPO_NAME: "laravel-app"
    ECS_CONTAINER_NAME: "laravel-app"

phases:
  pre_build:
    commands:
      - echo "===== Setting Environment Variables ====="
      - ECR_BASE_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_REPO_URI="${ECR_BASE_URL}/${ECR_REPO_NAME}"
      - ECR_COMMIT_HASH="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)"
      - ECR_IMAGE_TAG="${ECR_COMMIT_HASH:=latest}"

      - echo "AWS_REGION        = $AWS_REGION"
      - echo "AWS_ACCOUNT_ID    = $AWS_ACCOUNT_ID"
      - echo "ECR_REPO_NAME     = $ECR_REPO_NAME"
      - echo "ECR_IMAGE_TAG     = $ECR_IMAGE_TAG"
      - echo "ECR_BASE_URL      = $ECR_BASE_URL"
      - echo "ECR_REPO_URI      = $ECR_REPO_URI"

      - echo "===== Logging in to Amazon ECR ====="
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_BASE_URL"

  build:
    commands:
      - echo "===== Building the Docker Image ====="
      - docker build --target php_production -t "$ECR_REPO_URI" -t "$ECR_REPO_URI:latest" -t "$ECR_REPO_URI:$ECR_BASE_URL" .

  post_build:
    commands:
      - echo "===== Pushing the Docker Image ====="
      - docker push "$ECR_REPO_URI:latest"

      - echo "===== Writing image definitions file ====="
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECS_CONTAINER_NAME" "${ECR_REPO_URI}:${ECR_IMAGE_TAG}" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
